server:
  port: 8887
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application: 
    name: 'shopping-content-ms'
  datasource:
    username: root
    password: 123456
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=UTF-8'
    type: com.alibaba.druid.pool.DruidDataSource 
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb

pagehelper:
  helper-dialect: mysql
  reasonable: true
file:
  staticAccessPath: '/upload/**'
  uploadFolder: 'D:\\file'

 